name: meditrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.8.3
  path_provider: ^2.0.15
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  go_router: ^17.0.1
  intl: ^0.20.2
  provider: ^6.1.5+1

  # --- ADDED FOR DEVELOPER B: REMINDERS & LOGIC ---
  # Core for scheduling medication alarms
  flutter_local_notifications: ^16.3.0 
  # Required for accurate time scheduling across zones
  timezone: ^0.9.2
  # To detect internet status for your SyncStatus logic
  connectivity_plus: ^5.0.2
  # For the Either<Failure, Success> pattern in Repositories
  dartz: ^0.10.1
  # To generate unique IDs for reminders and history entries
  uuid: ^4.2.1
  # For value equality in your Models (prevents UI rebuild bugs)
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true